### ISSUE TITLE
Throwing warnings on "item with same key" instead of exception

### ISSUE THREAD

**Issue by YakaryBovine** [Drake53/War3Net#26]
I'm getting the following error when I try to build my map. This only happens to the Azeroth Wars map; it doesn't occur if I do the same operation on another source .w3x.

I don't doubt that the error is correct; my map data is probably broken in some respect. But I also don't have any way to fix that data, so I wonder - can this exception be changed to a warning instead of a program-stopping exception?

```System.ArgumentException: An item with the same key has already been added. Key: gg_dest_DRfc_21430
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at War3Net.CodeAnalysis.Transpilers.JassToLuaTranspiler.RegisterVariableType(IVariableDeclaratorSyntax declarator, Boolean isLocalDeclaration)
   at War3Net.CodeAnalysis.Transpilers.JassToLuaTranspiler.Transpile(IVariableDeclaratorSyntax declarator, Boolean isLocalDeclaration)
   at War3Net.CodeAnalysis.Transpilers.JassToLuaTranspiler.Transpile(JassGlobalDeclarationSyntax globalDeclaration)
   at War3Net.CodeAnalysis.Transpilers.JassToLuaTranspiler.<Transpile>b__52_2(IGlobalDeclarationSyntax declaration)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at CSharpLua.LuaAst.LuaSyntaxList`1.AddRange(IEnumerable`1 collection)
   at War3Net.CodeAnalysis.Transpilers.JassToLuaTranspiler.Transpile(JassCompilationUnitSyntax compilationUnit)
   at War3Net.Build.Extensions.MapExtensions.CompileScript(Map map, Compiler compiler, MapScriptBuilder mapScriptBuilder, IEnumerable`1 luaSystemLibs, String commonJPath, String blizzardJPath)
   at War3Net.Build.Extensions.MapExtensions.CompileScript(Map map, Compiler compiler, IEnumerable`1 luaSystemLibs, String commonJPath, String blizzardJPath)
   at AzerothWarsCSharp.Launcher.Program.Build(String baseMapPath, String projectFolderPath, Boolean launch) in C:\Users\Zak\source\repos\AzerothWarsCSharpNew\src\AzerothWarsCSharp.Launcher\Program.cs:line 131
   at AzerothWarsCSharp.Launcher.Program.MakeDecision() in C:\Users\Zak\source\repos\AzerothWarsCSharpNew\src\AzerothWarsCSharp.Launcher\Program.cs:line 80
   at AzerothWarsCSharp.Launcher.Program.Main() in C:\Users\Zak\source\repos\AzerothWarsCSharpNew\src\AzerothWarsCSharp.Launcher\Program.cs:line 59
```

**Comment by Drake53** [comment]
Did a quick test in world editor and surprisingly local variable identifiers can be duplicate (not just by shadowing global variables but also multiple local variables with the same identifier). However for global variables it is a syntax error, so in my opinion an exception is the correct way to handle it.

Since the duplicate identifier was gg_dest_... I think the easiest way to fix it would be to edit your war3map.doo file. If you look at https://github.com/Drake53/War3Net/blob/master/src/War3Net.Build/Extensions/DoodadDataExtensions.cs you see that the doodad's identifier is created using the CreationNumber, so all you need to do is make sure it's unique (for example 'for (var i = 0; i < count; i++) doodads[i].CreationNumber = i + 1').

**Comment by YakaryBovine** [comment]
Huh ok, I wouldn't have thought of that solution. But it worked great! Cheers.
