### ISSUE TITLE
Value '3' is not defined for enum of type ObjectDataFormatVersion

### ISSUE THREAD

**Issue by YakaryBovine** [Drake53/War3Net#31]
Perhaps unsurprisingly, the latest WC3 update broke the tool. When I attempt to build a map that has been edited with the latest Warcraft 3 editor, I get this: 

`Please type the number of your desired action: 2Unhandled exception. System.IO.InvalidDataException: Value '3' is not defined for enum of type ObjectDataFormatVersion.
   at War3Net.Common.Extensions.BinaryReaderExtensions.ToEnum[TEnum](Int32 i)
   at War3Net.Build.Object.AbilityObjectData.ReadFrom(BinaryReader reader)
   at War3Net.Build.Object.AbilityObjectData..ctor(BinaryReader reader)
   at War3Net.Build.Object.MapAbilityObjectData..ctor(BinaryReader reader)
   at War3Net.Build.Extensions.BinaryReaderExtensions.ReadMapAbilityObjectData(BinaryReader reader)
   at War3Net.Build.Map..ctor(String mapName, String mapFolder, MapFiles mapFiles)
   at War3Net.Build.Map.Open(String path, MapFiles mapFiles)
   at Launcher.Program.Build(Boolean launch) in C:\Users\zakar\RiderProjects\Autobattle\Launcher\Program.cs:line 77
   at Launcher.Program.MakeDecision() in C:\Users\zakar\RiderProjects\Autobattle\Launcher\Program.cs:line 58
   at Launcher.Program.Main() in C:\Users\zakar\RiderProjects\Autobattle\Launcher\Program.cs:line 43
`

**Comment by Drake53** [comment]
Duplicate of #29
Sorry, I haven't updated the nuget packages yet.

**Comment by YakaryBovine** [comment]
My bad, thankyou!
