### ISSUE TITLE
Compiler can crash rather than offering error message

### ISSUE THREAD

**Issue by thomaswp** [Drake53/War3Net#37]
I ran into [an issue](https://github.com/yanghuan/CSharp.lua/issues/406) with CSharp.lua that was creating an error during compilation.

However, it was tough to track down because when I use `Map.CompileScript`, it gives a rather opaque error message:

```
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=War3Net.Build
  StackTrace:
   at War3Net.Build.CompileResult..ctor(EmitResult emitResult)
   at War3Net.Build.Extensions.MapExtensions.CompileScript(Map map, Compiler compiler, MapScriptBuilder mapScriptBuilder, IEnumerable`1 luaSystemLibs, String commonJPath, String blizzardJPath)
   at War3Net.Build.Extensions.MapExtensions.CompileScript(Map map, Compiler compiler, IEnumerable`1 luaSystemLibs, String commonJPath, String blizzardJPath)
   at Launcher.Program.Build(Boolean launch) in C:\Users\Thomas\Desktop\WCSharpTemplate\Launcher\Program.cs:line 98
```

My guess is that there's a CompilationErrorException during compilation [here](https://github.com/Drake53/War3Net/blob/master/src/War3Net.Build/Extensions/MapExtensions.cs#L124) and for whatever reason, `e.EmitResult` is null, and contains no information. That then gives the NullReferenceException in the `CompileResult` constructor. But I don't have an internal stack trace, so I can't be sure.

Anyway, the error I hit was an unusual one, so maybe it's handled differently, but you can reproduce it like I described [here](https://github.com/yanghuan/CSharp.lua/issues/406). I'm using [WCSharp](https://github.com/Orden4/WCSharp)'s template.

Thanks as always for your work - this is a great tool!

**Comment by Drake53** [comment]
Thanks for reporting this, the exception has contructors that don't take an EmitResult, but didn't realize this because the property isn't nullable.
Fixed in v5.6.0.1 with this: https://github.com/Drake53/War3Net/commit/7707263748c0e3a3052fec74390009858fef30b9
